#include<stdio.h>
#include<conio.h>

void main ()
{
	clrscr();
	int b1;
	float b2;
	printf("Enter units: ");
	scanf("%d",&b1);

	if (b1<=100)
	{

		b2 = b1 * 1.80;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>100)&&(b1<=250))
	{

		b2=b1*3.40;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>250)&&(b1<=400))
	{

		b2=b1*4.90;
		printf("The total bill of customer is %f", b2);

	}

	else if (b1>400)
	{

		b2=b1*5.50;
		printf("The total bill of customer is %f", b2);

	}

	printf("\n\nEnter units: ");
	scanf("%d",&b1);

	if (b1<=100)
	{

		b2 = b1 * 1.80;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>100)&&(b1<=250))
	{

		b2=b1*3.40;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>250)&&(b1<=400))
	{

		b2=b1*4.90;
		printf("The total bill of customer is %f", b2);

	}

	else if (b1>400)
	{

		b2=b1*5.50;
		printf("The total bill of customer is %f", b2);

	}

	printf("\n\nEnter units: ");
	scanf("%d",&b1);

	if (b1<=100)
	{

		b2 = b1 * 1.80;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>100)&&(b1<=250))
	{

		b2=b1*3.40;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>250)&&(b1<=400))
	{

		b2=b1*4.90;
		printf("The total bill of customer is %f", b2);

	}

	else if (b1>400)
	{

		b2=b1*5.50;
		printf("The total bill of customer is %f", b2);

	}

	printf("\n\nEnter units: ");
	scanf("%d",&b1);

	if (b1<=100)
	{

		b2 = b1 * 1.80;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>100)&&(b1<=250))
	{

		b2=b1*3.40;
		printf("The total bill of customer is %f", b2);

	}

	else if ((b1>250)&&(b1<=400))
	{

		b2=b1*4.90;
		printf("The total bill of customer is %f", b2);

	}

	else if (b1>400)
	{

		b2=b1*5.50;
		printf("The total bill of customer is %f", b2);

	}

	getch();

}



