#include <stdio.h>
#include <math.h>

int main()
{

	printf("enter a number =\t");

	int n1, s, s2, s3, s4, s5, s6, s7, s8, s9, s10;

	scanf("%d", &n1);

	s = n1 * 1;

	printf("\n%d * 1 = %d\n\n", n1, s);

	s2 = n1 * 2;

	printf("%d * 2 = %d\n\n", n1, s2);

	s3 = n1 * 3;

	printf("%d * 3 = %d\n\n", n1, s3);

	s4 = n1 * 4;

	printf("%d * 4 = %d\n\n", n1, s4);

	s5 = n1 * 5;

	printf("%d * 5 = %d\n\n", n1, s5);

	s6 = n1 * 6;

	printf("%d * 6 = %d\n\n", n1, s6);

	s7 = n1 * 7;

	printf("%d * 7 = %d\n\n", n1, s7);

	s8 = n1 * 8;

	printf("%d * 8 = %d\n\n", n1, s8);

	s9 = n1 * 9;

	printf("%d * 9 = %d\n\n", n1, s9);

	s10 = n1 * 10;

	printf("%d * 10 = %d\n\n", n1, s10);

	printf("%d < %d < %d < %d < %d < %d < %d < %d < %d < %d", s, s2, s3, s4, s5, s6, s7, s8, s9, s10);

	return 0;
}
